export const FETCH_REQUEST = 'FETCH_REQUEST'
export const FETCH_SUCCESS = 'FETCH_SUCCESS'
export const FETCH_FAILURE = 'FETCH_FAILURE'
export const FETCH_QUERY = 'FETCH_QUERY';
export const SEARCH_QUERY = 'SEARCH_QUERY';
export const SEARCH_OPTION = 'SEARCH_OPTION';